anytv_community:
    resource: "@AnytvCommunityBundle/Resources/config/routing.yml"
    prefix:   /community

anytv_main:
    resource: "@AnytvMainBundle/Resources/config/routing.yml"
    prefix:   /

anytv_dashboard:
    resource: "@AnytvDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard
    
login:
    path:  /login/{_locale}
    defaults: { _controller: AnytvDashboardBundle:Security:login, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
login_hasoffers:
    path:  /login/hasoffers/{_locale}
    defaults: { _controller: AnytvDashboardBundle:Security:loginHasoffers, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
login_check:
    path:  /login_check/{_locale}
    requirements:
        _locale:  %anytv.locales%
    
logout:
    path:   /logout
    
offers_embed:
    path:      /{_locale}/embed/offers/{page}
    defaults:  { _controller: AnytvDashboardBundle:Offer:embed, _locale: en, page: 1 }
    requirements:
        _locale:  %anytv.locales%
        page:  \d+
        
_imagine:
    resource: .
    type:     imagine

