anytv_community:
    resource: "@AnytvCommunityBundle/Resources/config/routing.yml"
    prefix:   /community

anytv_main:
    resource: "@AnytvMainBundle/Resources/config/routing.yml"
    prefix:   /

anytv_dashboard:
    resource: "@AnytvDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

