anytv_main_homepage:
    path:  /{_locale}
    defaults: { _controller: AnytvMainBundle:Default:index, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
news_reset:
    path:      /{_locale}/admin/news/reset
    defaults:  { _controller: AnytvMainBundle:News:reset, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
news:
    path:      /{_locale}/admin/news/{page}
    defaults:  { _controller: AnytvMainBundle:News:index, _locale: en, page: 1 }
    requirements:
        _locale:  %anytv.locales%
        page:  \d+
       
news_add:
    path:      /{_locale}/admin/news/add
    defaults:  { _controller: AnytvMainBundle:News:add, _locale: en }
    requirements:
        _locale:  %anytv.locales%
    
news_edit:
    path:      /{_locale}/admin/news/edit/{id}
    defaults:  { _controller: AnytvMainBundle:News:edit, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        id:  \d+
    
news_category:
    path:      /{_locale}/admin/news/categories/{page}
    defaults:  { _controller: AnytvMainBundle:NewsCategory:index, _locale: en, page: 1 }
    requirements:
        _locale:  %anytv.locales%
        page:  \d+
        
news_category_add:
    path:      /{_locale}/admin/news/categories/add
    defaults:  { _controller: AnytvMainBundle:NewsCategory:add, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
news_category_edit:
    path:      /{_locale}/admin/news/categories/edit/{id}
    defaults:  { _controller: AnytvMainBundle:NewsCategory:edit, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        id:  \d+
