parameters:
#    anytv_main.example.class: Anytv\MainBundle\Example

services:
#    anytv_main.example:
#        class: %anytv_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
